### ISSUE TITLE
Impressive work

### ISSUE THREAD

**Issue by sokoow** [nohkwangsun/kubrightics#1]
Hi,

I found your hdfs screencast for spark hdfs: https://asciinema.org/a/37553 . Pretty impressive work! :D I got one quick question, I can see that you published your docker containers, fair play to you :) Do you also plan to publish your kubernetes yaml files as well ? :) I'm planning to recreate your environment and submit some improvements back.

Greetings

**Comment by nohkwangsun** [comment]
Hi,

you can find the yaml files in our company's github repos.
https://github.com/Samsung-AG/spark-kubernetes-demo/tree/master/spark-kubernetes-demo

And.. the screencast you can saw has some mistakes, I’m recording again and you can see the perfect one soon.

Thank you.

**Comment by sokoow** [comment]
There's some files missing in this mentioned repo - kube-up.sh is not there, as well as yaml files for hdfs version of demo

**Comment by nohkwangsun** [comment]
I’m sorry. You’re right.
I had a mistake.

I will push the files next week (before Mar.5)

As you see in the asciinema, there are some problems.
After I fix all problems, I will push the files.

Before that, Below links can help you.

https://github.com/Samsung-AG/spark-kubernetes-demo/tree/master/spark-kubernetes-demo https://github.com/Samsung-AG/spark-kubernetes-demo/tree/master/spark-kubernetes-demo
http://kubernetes.io/v1.1/examples/spark/README.html http://kubernetes.io/v1.1/examples/spark/README.html
https://github.com/sequenceiq/hadoop-docker https://github.com/sequenceiq/hadoop-docker

**Comment by sokoow** [comment]
Hey, did you release these files yet ? :D

**Comment by nohkwangsun** [comment]
I had uploaded all files last week.
https://github.com/Samsung-AG/spark-kubernetes-demo/tree/master/spark-demo
